[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_auto_colors = 0
        autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=239
        autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237
    let g:indent_guides_guide_size = 1
    let g:indent_guides_start_level =2
'''

[[plugins]]
repo = 'Shougo/unite.vim'
hook_source = '''
    let g:unite_dir = $HOME . '/.config/nvim/config/setting/unite/'
    exec "source " . g:unite_dir . 'setting.vim'
'''

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
    let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.vue,*.rb'
'''

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'one',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex' ] ]
      \ },
      \ 'component': {
      \   'charvaluehex': '0x%B',
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead',
      \ },
      \ }
'''

# [[plugins]]
# repo = 'scrooloose/nerdtree'
# hook_add = '''
#     nnoremap <leader>n :NERDTreeFocus<CR>
#     nnoremap <C-n> :NERDTree<CR>
#     nnoremap <C-t> :NERDTreeToggle<CR>
#     nnoremap <C-f> :NERDTreeFind<CR>
#     let g:NERDTreeShowHidden=1
#     let g:NERDTreeQuitOnOpen=1
#     let g:NERDTreeIgnore=['\.git$', '\.clean$', '\.swp$', '\.bak$', '\~$']
#     let g:NERDTreeDirArrowExpandable = '  ▸'
#     let g:NERDTreeDirArrowCollapsible = '  ▾'
#     let g:NERDTreeShowLineNumbers = 1
# '''
