[[plugins]]
repo = 'neoclide/coc.nvim'
branch = 'release'
merged = 0

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
tag = '0.1.x'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=239
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237
  let g:indent_guides_guide_size = 1
  let g:indent_guides_start_level =2
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# status line
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'

#filer
[[plugins]]
repo = "nvim-neo-tree/neo-tree.nvim"
hook_add = '''
  let g:neo_tree_remove_legacy_commands = 1
'''
[[plugins]]
repo = "MunifTanjim/nui.nvim"
