[[plugins]]
repo = 'Shougo/dein.vim'

# lsp
[[plugins]]
repo = 'neovim/nvim-lspconfig'
[[plugins]]
repo = 'williamboman/mason.nvim' 
[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'hrsh7th/cmp-path'
[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = "Saecki/crates.nvim"
tag = "v3.0.0"
lua_add = '''
require('crates').setup()
'''

# Fuzzy Finder
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
tag = '0.1.x'
[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# convinient
[[plugins]]
repo = 'tpope/vim-commentary'
[[plugins]]
repo = 'windwp/nvim-autopairs'
lua_add = '''
require("nvim-autopairs").setup {}
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
local cmp = require('cmp')
cmp.event:on(
  'confirm_done',
  cmp_autopairs.on_confirm_done()
)
'''
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'easymotion/vim-easymotion'


# tag
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
let g:closetag_enable_react_fragment = 1
'''

# terminal
[[plugins]]
repo = "akinsho/toggleterm.nvim"
lua_add = '''
  require('toggleterm').setup()
'''

###################### appearance ############################

# status line
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
[[plugins]]
repo = 'arkav/lualine-lsp-progress'


# cursor move
[[plugins]]
repo = 'gen740/SmoothCursor.nvim'
lua_add='''
require('smoothcursor').setup({
  speed = 50,
  fancy = {
    enable = true,       -- enable fancy mode
    head = { cursor = "▷", texthl = "SmoothCursor", linehl = nil },
    body = {
      { cursor = "", texthl = "SmoothCursorRed" },
      { cursor = "", texthl = "SmoothCursorOrange" },
      { cursor = "●", texthl = "SmoothCursorYellow" },
      { cursor = "●", texthl = "SmoothCursorGreen" },
      { cursor = "•", texthl = "SmoothCursorAqua" },
      { cursor = ".", texthl = "SmoothCursorBlue" },
      { cursor = ".", texthl = "SmoothCursorPurple" },
    },
    tail = { cursor = nil, texthl = "SmoothCursor" }
  },
})
'''

# indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=239
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237
  let g:indent_guides_guide_size = 1
'''
