[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = ['telescope.nvim']

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
" let g:denops_server_addr = '127.0.0.1:32123'
'''
[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'

# on_source = ['gin.vim', 'ddc.vim', 'denops-popup-preview.vim', 'denops-helloworld.vim']
[[plugins]]
repo = 'lambdalisue/mr.vim'
