[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim']


[[plugins]]
repo = 'williamboman/mason.nvim' 
build = ':MasonUpdate'
depends = ['nvim-lspconfig']
lua_source = '''
require('dein.lspserver')
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim']

