[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim']

[[plugins]]
repo = 'williamboman/mason.nvim' 
build = ':MasonUpdate'
depends = ['nvim-lspconfig']

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig']
lua_add = '''
require('dein.lspserver')
'''

