[[plugins]]
repo = 'Shougo/ddu-commands.vim'
hook_add = '''
nnoremap <silent> <leader>ff <Cmd>Ddu file_rec<CR>
nnoremap <silent> <leader>fo <Cmd>Ddu file_old<CR>
nnoremap <silent> <leader>fg <Cmd>Ddu rg<CR>
nnoremap <silent> <leader>fb <Cmd>Ddu buffer<CR>
nnoremap <silent> <leader>fh <Cmd>Ddu help<CR>
nnoremap <silent> <leader>fr <Cmd>Ddu mr<CR>
nnoremap <silent> <leader>fm <Cmd>Ddu man<CR>
nnoremap <silent> <leader>fc <Cmd>Ddu colorscheme -ui-param-winWidth=&columns*3/4<CR>
'''

[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = '''
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'uiParams': {
    \     'ff': {
    \        'previewFloating': v:true,
    \        'previewSplit': "vertical",
    \        'previewHeight': &lines - 8,
    \        'previewWidth': &columns * 3 / 8,
    \        'previewRow': 3,
    \        'filterSplitDirection': 'floating',
    \        'winWidth': &columns * 3 / 8,
    \        'winCol': &columns / 8,
    \        'winRow': 3,
    \        'winHeight': &lines - 8,
    \        'split': 'floating',
    \        'startFilter': v:true,
    \        'autoAction': {
    \          'name': 'preview',
    \        },
    \        'prompt': '>> ',
    \     },
    \   },
    \   'sources': [
    \        {'name': 'file_rec', 'params': {}},
    \        {'name': 'file_old', 'params': {}},
    \        {'name': 'rg', 'params': {}},
    \        {'name': 'buffer', 'params': {}},
    \        {'name': 'help', 'params': {}},
    \        {'name': 'mr', 'params': {}},
    \        {'name': 'man', 'params': {}},
    \        {'name': 'colorscheme', 'params': {}},
    \   ],
    \   'sourceParams': {
    \     'rg': {
    \       'args' : ['--json'],
    \     },
    \     'file_rec': #{
    \       expandSymlinks: v:true,
    \       ignoredDirectories: [".git", "venv", ".vscode", ".ccls-cache"],
    \     },
    \   },
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_fzf'],
    \       'ignoreCase': v:true,
    \     },
    \     'man': {
    \       'volatile': v:true,
    \     },
    \     'rg': {
    \       'matchers': ['converter_display_word'],
    \       'volatile': v:true,
    \     },
    \   },
    \   'filterParams': {
    \     'matcher_fzf': {
    \       'highlightMatched': 'Search',
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \     'man': {
    \       'defaultAction': 'open',
    \     },
    \     'help': {
    \       'defaultAction': 'open',
    \     },
    \     'colorscheme': {
    \       'defaultAction': 'set',
    \     },
    \   },
    \  'kindParams': {
    \     'help': {
    \       'command': 'vsplit',
    \     },
    \   },
    \ 
    \ })
'''



[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[plugins.ftplugin]
ddu-ff = '''
  nnoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> :q<CR>
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  nnoremap <buffer><silent> q
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  nnoremap <buffer><silent> p
        \ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
  nnoremap <buffer><silent> <C-e>
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''

ddu-ff-filter = '''
  " execute("call ddu#ui#ff#do_action('preview')")
  inoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR><esc>
  imap <buffer><silent> <esc>
        \ <esc><Cmd>close<CR>
  inoremap <buffer><silent> <C-e>
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  inoremap <buffer> <C-d>
        \ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
  inoremap <buffer> <C-n>
        \ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')+1,0)<Bar>redraw")<CR>
  inoremap <buffer> <C-p>
        \ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')-1,0)<Bar>redraw")<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
[[plugins]]
repo = 'Shougo/ddu-source-file_old'
[[plugins]]
repo = 'shun/ddu-source-rg'
[[plugins]]
repo = 'shun/ddu-source-buffer'
[[plugins]]
repo = 'matsui54/ddu-source-help'
[[plugins]]
repo = 'kuuote/ddu-source-mr'
[[plugins]]
repo = 'matsui54/ddu-source-man'
[[plugins]]
repo = '4513ECHO/ddu-source-colorscheme'

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
[[plugins]]
repo = 'Shougo/ddu-kind-file'
