[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
on_event = ['InsertEnter', 'CommandLineEnter']
hook_post_source = '''
" Customize global settings

call ddc#custom#patch_global({
    \ 'ui': 'pum',
    \ 'sources': ['nvim-lsp', 'around'],
    \ 'sourceOptions': #{
    \   _: #{
      \   matchers: ['matcher_fuzzy'],
      \   sorters: ['sorter_fuzzy'],
      \   converters: ['converter_fuzzy']
      \ },
    \   around: #{ mark: 'A' },
    \   nvim-lsp: #{
    \     mark: 'lsp',
    \     forceCompletionPattern: '\.\w*|:\w*|->\w*' 
    \   },
    \ },
    \ 
    \ 'sourceParams' : #{
    \   around: #{ maxSize: 500 },
    \ }
    \})


" <TAB>: completion.
inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#map#manual_complete()

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

" Use ddc.
call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
depends = ['denops.vim', 'ddc.vim']
on_source = ['ddc.vim']

[[plugins]]
repo = 'tani/ddc-fuzzy'
depends = ['denops.vim', 'ddc.vim']
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-around'
depends = ['denops.vim', 'ddc.vim']
on_source = ['ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
depends = ['denops.vim', 'ddc.vim']
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/pum.vim'
depends = ['denops.vim', 'ddc.vim']
on_source = ['ddc.vim']
hook_post_source = '''
inoremap <C-n>   <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p>   <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <Tab>   <Cmd>call pum#map#confirm()<CR>
inoremap <C-e>   <Cmd>call pum#map#cancel()<CR>
inoremap <PageDown> <Cmd>call pum#map#insert_relative_page(+1)<CR>
inoremap <PageUp>   <Cmd>call pum#map#insert_relative_page(-1)<CR>
'''

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['denops.vim', 'ddc.vim', 'pum.vim']
on_source = ['ddc.vim']

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim', 'ddc.vim']
on_source = ['ddc.vim']
hook_post_source = '''
call popup_preview#enable()
'''
