[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
hook_add = '''
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'uiParams': {
    \     'previewFloating': v:true,
    \     'split': 'floating',
    \     'startFilter': v:true,
    \     'prompt': '> ',
    \     'winCol': &columns / 8,
    \     'winHeight': 40,
    \     'winRow': &lines / 4 - 8,
    \     'winWidth': &columns * 3 / 4,
    \   },
    \   'sources': [{'name': 'file_rec', 'params': {}}],
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \       'ignoreCase': v:true,
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   }
    \ })
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = ['ddu.vim', 'denops.vim']

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
depends = ['ddu.vim', 'denops.vim']
hook_add = '''
autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
  nnoremap <buffer><silent> q
  \ <Cmd>close<CR>
endfunction
nnoremap <silent> <leader>dd <Cmd>Ddu file_rec<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
depends = ['ddu.vim', 'denops.vim']
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
depends = ['ddu.vim', 'denops.vim']
[[plugins]]
repo = 'Shougo/ddu-kind-file'
depends = ['ddu.vim', 'denops.vim']
