[[plugins]]
repo = 'neoclide/coc.nvim'
branch = 'release'
merged = 0

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
tag = '0.1.x'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=239
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237
  let g:indent_guides_guide_size = 1
  let g:indent_guides_start_level =2
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# session
[[plugins]]
repo = 'xolox/vim-misc'
[[plugins]]
repo = 'xolox/vim-session'
hook_add = '''
" 現在のディレクトリ直下の .vimsessions/ を取得 
let s:local_session_directory = xolox#misc#path#merge(getcwd(), '.vimsessions')
" 存在すれば
if isdirectory(s:local_session_directory)
  " session保存ディレクトリをそのディレクトリの設定
  let g:session_directory = s:local_session_directory
  " vimを辞める時に自動保存
  let g:session_autosave = 'yes'
  " 引数なしでvimを起動した時にsession保存ディレクトリのdefault.vimを開く
  let g:session_autoload = 'yes'
  " 1分間に1回自動保存
  let g:session_autosave_periodic = 1
else
  let g:session_autosave = 'no'
  let g:session_autoload = 'no'
endif
'''

# status line
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'

#filer
[[plugins]]
repo = "nvim-neo-tree/neo-tree.nvim"
hook_add = '''
  let g:neo_tree_remove_legacy_commands = 1

  autocmd StdinReadPre * let s:std_in=1
  autocmd VimEnter * if argc() == 0 && !exists('s:std_in') && v:this_session == '' | exe ':Neotree current' | endif
  nnoremap <C-t> :Neotree toggle right<CR>

  " 選択したら画面を消す
  " focusされていない状態でtoggleはfocusにする
'''
[[plugins]]
repo = "MunifTanjim/nui.nvim"
